<?php
session_start();
include("logincheck.php");
require 'connect.php';

$id  = $_GET['id']; //ID of exhibit to delete

//QUERIES TO MAKE
//1 DELETE ALL ENTRIES IN ARTISTS_EXHIBITS THAT HAVE EXHIBIT ID OF $ID
//2 DELETE ALL ENTRIES IN CATEGORY_EXHIBITS THAT HAVE EXHIBIT ID OF $ID
//3 DELETE ALL EXHIBITS IN EXHIBITS THAT HAVE EXHIBIT ID OF $ID
//4 DELETE ALL FILES IN FILES THAT HAVE EXHIBIT_ID OF $ID (AND UNSET FROM SERVER)
//5 DELETE ALL IMAGES FROM IMAGES THAT HAVE EXHIBIT ID OF $ID


$REMOVEQUERY_ARTISTS_EXHIBITS = "DELETE FROM ARTISTS_EXHIBITS WHERE EXHIBIT_ID = $id";
$REMOVEQUERY_CATEGORY_EXHIBITS = "DELETE FROM CATEGORY_EXHIBITS WHERE EXHIBIT_ID = $id";
$REMOVEQUERY_EXHIBITS = "DELETE FROM EXHIBITS WHERE ID = $id";
$REMOVEQUERY_FILES = "DELETE FROM FILES WHERE EXHIBIT_ID = $id";
$REMOVEQUERY_IMAGES = "DELETE FROM FILES WHERE EXHIBIT_ID = $id";

$GETFILES = "SELECT * FROM IMAGES WHERE EXHIBIT_ID = $id";
$DELETERESULT = mysqli_query($mysqli, $GETFILES);

while ($row = mysqli_fetch_array($DELETERESULT)) {
  unlink($row['PATH']);
}





$result1 = mysqli_query($mysqli, $REMOVEQUERY_ARTISTS_EXHIBITS);
$result2 = mysqli_query($mysqli, $REMOVEQUERY_CATEGORY_EXHIBITS);
$result3 = mysqli_query($mysqli, $REMOVEQUERY_EXHIBITS);
$result4 = mysqli_query($mysqli, $REMOVEQUERY_FILES);
$result5 = mysqli_query($mysqli, $REMOVEQUERY_IMAGES);

$_SESSION['DELETE'] = true;
header("Location: ../../pages/tables.php");
 ?>